### ISSUE TITLE
Move sample payment & shipment methods & tax provider to separate module

### ISSUE THREAD

**Issue by asvishnyakov** [VirtoCommerce/vc-module-core#101]
(And rename them, because they are not default, they are just sample)

Currently I need to explain to clients why they have them and what they need to disable them on production.

**Comment by eMazeika** [comment]
Optionally, there could be a global setting to control which functionallity is enabled. Only the selected features whould be registered at system startup.

**Comment by asvishnyakov** [comment]
@eMazeika if you mean what we may use them as go-live solution for shipping/taxes with fixed rates, then we have different requirements for them: we need double check what they are ready for that, write tests, probably rename them and more.

**Comment by tatarincev** [comment]
No longer relevant for the platform 3.0.
