### ISSUE TITLE
Change markdown dialog to split mode when maximized

### ISSUE THREAD

**Issue by OlegoO** [VirtoCommerce/vc-module-core#11]
@Woland2k commented on [Wed Sep 20 2017](https://github.com/VirtoCommerce/vc-platform/issues/1165)

Currently when maximized, markdown view is displayed with tabs (markdown and preview) which need to be switched manually to see how content looks like:
![image](https://user-images.githubusercontent.com/1566470/30629932-2ec45818-9d93-11e7-8510-eb16dc58ab2c.png)

Change this to split view instead when certain width is reached so there is no need to manually switched to preview mode when editing content (it is a setting of the control).

![image](https://user-images.githubusercontent.com/1566470/30630121-0653c8ae-9d94-11e7-8977-d74619006f70.png)

**Comment by OlegoO** [comment]
![image](https://user-images.githubusercontent.com/7639413/30740215-6ece2d72-9f90-11e7-938f-60a6dfd8e560.png)

![image](https://user-images.githubusercontent.com/7639413/30740261-968d8ccc-9f90-11e7-88e0-7cb058c9c019.png)

**Comment by Woland2k** [comment]
Need to make sure this also works in the product description view.

**Comment by OlegoO** [comment]
@Woland2k , I tested in the product description view.

![image](https://user-images.githubusercontent.com/7639413/30747194-bb008cf0-9fac-11e7-8c57-722d1f2511fa.png)

![image](https://user-images.githubusercontent.com/7639413/30747213-c74d97c8-9fac-11e7-84c8-afad10e4f8fb.png)
