### ISSUE TITLE
Indexation still continues in background when canceled

### ISSUE THREAD

**Issue by WimVergouwe** [VirtoCommerce/vc-module-core#112]
### Expected behavior
Indexation should stop completely when canceled through the UI or when the job is deleted.

### Actual behavior
Indexation process still continues, searchprovider still gets documents to index.

### Steps to reproduce
1. Start indexation in UI
2. Cancel the indexation
3. Look at logging

PS: tested with scaled-out indexation

**Comment by yecli** [comment]
[v2.25.20](https://github.com/VirtoCommerce/vc-module-core/releases/tag/v2.25.20)
