### ISSUE TITLE
Add bulk operations for indexation

### ISSUE THREAD

**Issue by asvishnyakov** [VirtoCommerce/vc-module-core#113]
Sometime we need to reindex few products. We already have an ability to reindex single product and ability to reindex all products, but we need also ability to reindex few products only, for example a result of search.

**Comment by Woland2k** [comment]
@5309  this is part of the bulk feature

**Comment by asvishnyakov** [comment]
@Woland2k @5309 Related to #99

**Comment by tatarincev** [comment]
This feature request has been closed and added to the internal product backlog. 
https://virtocommerce.atlassian.net/browse/PRD-47
