### ISSUE TITLE
Dummy search provider is not overridden by ElasticSearch provider

### ISSUE THREAD

**Issue by mvsmal** [VirtoCommerce/vc-module-core#137]
After the registration of `DummySearchProvider` in the commit https://github.com/VirtoCommerce/vc-module-core/commit/6690ea5f9ce2ec7e83dc47a7b68d411bbed4c617#diff-a78924c769c19f425227f58548137828R127 , any other registrations of `ISearchProvider` are not respected. `ElasticSearchProvider` registration is ignored.

Version info: 
- Browser version: any
- Platform version: 2.13.50
- Module version: 2.25.29

### Expected behavior
Specific search provider registration is respected by Unity.

### Actual behavior
`DummySearchProvider` is resolved as the registered implementation of `ISearchProvider`.

### Steps to reproduce
1. Install ElasticSearch module
2. Run application
3. Try to resolve `ISearchProvider` in a service, e.g. `ProductSearchService`

**Comment by yecli** [comment]
Fixed in https://github.com/VirtoCommerce/vc-module-elastic-search/releases/tag/v1.2.2.
This module version works only with Elastic 7x.
Fix for Elastic 5x version will be released later, we will inform about it.

**Comment by yecli** [comment]
Release for Elastic 5x: 
https://github.com/VirtoCommerce/vc-module-elastic-search/releases/tag/v1.1.3
