### ISSUE TITLE
Indexed search: Add support of streamed (nonpaged) way for retrieve documents changes for indexation

### ISSUE THREAD

**Issue by tatarincev** [VirtoCommerce/vc-module-core#14]
The IIndexDocumentChangesProvider abstraction allows only to page through a set which is quite inefficient for NoSQL storages.
Need to adopt this interface to support a more simple streamed (IEnumerable) way of reading (changed) documents.

**Comment by WimVergouwe** [comment]
I've been playing around with an implementation based on a statefull feed. This allows us to efficiently page through a storage subsystem while still be able to support the old change provider interface.
I'll be sending a pull request soon if this is alright by you guys?

```csharp
    /// <summary>
    /// Allows creating a statefull change feed as a source for the indexation process.
    /// </summary>
    public interface IIndexDocumentChangeFeedFactory
    {
        /// <summary>
        /// Creates the change feed.
        /// </summary>
        /// <param name="startDate">Start date as a filter for the changes.</param>
        /// <param name="endDate">End date as a filter for the changes.</param>
        /// <param name="batchSize">Size of the batches to use.</param>
        /// <returns>Created feed, never null.</returns>
        Task<IIndexDocumentChangeFeed> CreateFeed(DateTime? startDate, DateTime? endDate, int batchSize);
    }

    /// <summary>
    /// Statefull change feed for indexation.
    /// Storage sub systems should be able to implement this effeciently, whether it be Sql or NoSql.
    /// </summary>
    public interface IIndexDocumentChangeFeed
    {
        /// <summary>
        /// Optional total count, feed is not required to implement this.
        /// This is only informational so that the user might have an idea how long the process will still take.
        /// </summary>
        long? TotalCount { get; }

        /// <summary>
        /// Gets the next batch with changes.
        /// </summary>
        /// <returns>Batch of changes or null when at end of feed.</returns>
        Task<IReadOnlyCollection<IndexDocumentChange>> GetNextBatch();
    }
```

Backwards compatibilty:
````csharp
    /// <summary>
    /// Implements IIndexDocumentChangeFeedFactory on top of the older IIndexDocumentChangesProvider
    /// to support backwards compatibility.
    /// </summary>
    public class IndexDocumentChangeFeedFactoryAdapter : IIndexDocumentChangeFeedFactory
    {
        protected IIndexDocumentChangesProvider Provider { get; }

        public IndexDocumentChangeFeedFactoryAdapter(IIndexDocumentChangesProvider provider)
        {
            Provider = provider ?? throw new ArgumentNullException(nameof(provider));
        }

        public virtual async Task<IIndexDocumentChangeFeed> CreateFeed(DateTime? startDate, DateTime? endDate, int batchSize)
        {
            var totalCount = await Provider.GetTotalChangesCountAsync(startDate, endDate);
            return new IndexDocumentChangeFeedForProvider(Provider, startDate, endDate, totalCount, batchSize);
        }

        protected class IndexDocumentChangeFeedForProvider : IIndexDocumentChangeFeed
        {
            protected IIndexDocumentChangesProvider Provider { get; }
            protected DateTime? StartDate { get; }
            protected DateTime? EndDate { get; }

            public long? TotalCount { get; set; }
            protected long Skip { get; set; }
            protected long Take { get; }

            public IndexDocumentChangeFeedForProvider(IIndexDocumentChangesProvider provider,
                DateTime? startDate, DateTime? endDate, long totalCount, long take)
            {
                Provider = provider ?? throw new ArgumentNullException(nameof(provider));
                StartDate = startDate;
                EndDate = endDate;
                TotalCount = totalCount;
                Take = take;
            }

            public async Task<IReadOnlyCollection<IndexDocumentChange>> GetNextBatch()
            {
                if (Skip >= TotalCount) return null;

                var changes = await Provider.GetChangesAsync(StartDate, EndDate, Skip, Take);
                if (changes.Count == 0) return null;

                Skip += changes.Count;

                return new ReadOnlyCollection<IndexDocumentChange>(changes);
            }
        }
    }
````

**Comment by tatarincev** [comment]
You already find the best solution. 👍 
 But need to make some changes before prepare PR.
1. `IIndexDocumentChangeFeedFactory` and `IIndexDocumentChangeFeed` will be used as default abstraction for works with changes and should replace current `IIndexDocumentChangesProvider` type.
Therefore need to mark `IIndexDocumentChangesProvider` as obsolete.
2. `IndexDocumentChangeFeedFactoryAdapter ` also need only for back compatibility and should have an internal visibility type, because it will be removed in future.
3. Need to change current `IndexManager` implementation to working with new `IIndexDocumentChangeFeed` iterator. (This code missing here but I hope to see it in your PR :))

**Comment by WimVergouwe** [comment]
1. This generates some build errors due to 'warning as errors'.
2. Doesn't this come in handy for other modules as well?
3. See PR ;)

I have also added background worker to increase indexation performance drastically.
Maybe we should increase default batch size as well, e.g. 500 instead of 50.
I have an implementation with events instead of scheduled job. Interested?

**Comment by tatarincev** [comment]
I have a question about indexation based on events. Am right understand what you did realtime indexation for catalog entities?

**Comment by WimVergouwe** [comment]
I hooked in events in the item service and pricing service and let the indexing manager index the changes queued. Makes sense?

**Comment by tatarincev** [comment]
I got it, to achieve it need to define events for each domain aggregate and in these events handlers make the indexation process. We use this approach in many modules and it one right way in my IMHO.

But the problem is there what I want to use another events framework instead what we currently have. I'm looking the following projects to get CQRS, Event and ES elements to reuse in our platform: 
https://github.com/eventflow/EventFlow - very interesting CQRS + ES framework implementation but very hard to use separate parts of this library. 
https://github.com/gautema/CQRSlite/tree/master/Framework/CQRSlite - contains all that we need and each part can be easily used separately (i.e Events and Handler, Commands, ES. Aggregates etc)

**Comment by WimVergouwe** [comment]
@tatarincev, I have been implementing a couple of CQRS architectures myself. Although I've never implemented a full ES system. But there are a couple of drawbacks to these architectures as well. I'm not really sure that the Virto Commerce case warrants going to a full CQRS + ES architecture, although I definitely see the benefit of CQRS, that would also allow intercepting each change in the system quite easily. But for now, can I just add the needed events and send PRs?

I've come across some interesting reads about CQRS + ES:
- http://udidahan.com/2011/04/22/when-to-avoid-cqrs/
- https://www.infoq.com/news/2016/04/event-sourcing-anti-pattern

Furthermore, what are your ideas about following topics?
- Integration testing: we set this up, but its quite nasty with all the difference git repos
- Performance: EF doesn't really ingest very well, which is typically something we need often: products, prices, stock
- Deployments: do you guys use blue-green deployments on Azure?

**Comment by tatarincev** [comment]
@WimVergouwe  Any PR is welcome, don't hesitate. Yes, I share your point of view about ES, it will be over-enginerring  for most modules functionality, but in some domain areas such as Order management this technology can be useful. 
Now answering on your questions
We use Docker with Jenkinse CI where preparing platform deployment with modules and run integrations tests on each commit in observed GitHub repository, alse we use Ghost inspector for record and run E2E tests on QA environment.

We looking to Dapper ORM for EF replacement for reading and queries data from DB, but it only in our plans, and we do nothing in this direction. Also EF Core promised to be ultrafast :). So we are waiting for now.
Yes, for almost all project we use blue-green deployment, Azure provide slots features and we use this very often for production update.
