### ISSUE TITLE
Order Number is not sequence

### ISSUE THREAD

**Issue by tonhuynh** [VirtoCommerce/vc-module-core#148]
Our server host on Azure with 2 instances, and our order-number field hasn't been sequence.
- Order number template: CO{0:yyMMdd}-{1:D5}

Version info: 
- Browser version: 
- Platform version: 2.13.44
- Module version: 2.25.18

### Expected behavior
OrderNumber must be sequence.

### Actual behavior
Order number wasn't

### Steps to reproduce
1. Commerce Manager: fixed 2 instances
2. Login to Storefront and create orders with multiple users, browsers as the same time.

### Reason:
1. using InMemorySequenceList won't share memory between commerce instances.
2. When we turn Off Cookies on Storefront, this issue will happen.

**Comment by yecli** [comment]
Current implementation guarantees number uniqueness (in case of a date part presented in the template) and increasing sequence in case of one platform instance.
The strict increasing sequence with customization will be implemented at https://github.com/VirtoCommerce/vc-module-core/issues/146 (it is in progress now).
It will be done in v3 first.

**Comment by tonhuynh** [comment]
Good to know that. Thanks @yecli
