### ISSUE TITLE
Proposal: Move index search helpers to Core module

### ISSUE THREAD

**Issue by asvishnyakov** [VirtoCommerce/vc-module-core#18]
Customer module has [useful extensions](https://github.com/VirtoCommerce/vc-module-customer/blob/master/VirtoCommerce.CustomerModule.Data/Search/Indexing/IndexDocumentExtensions.cs) for adding values to index document. Catalog module has not, so it contains some [code duplication](https://github.com/VirtoCommerce/vc-module-catalog/blob/dea152082fc4501186e9625dd978ac672adf20e6/VirtoCommerce.CatalogModule.Data/Search/Indexing/CategoryDocumentBuilder.cs) (L48-50, 57-52, 94-95). Find Store module will also have this extensions. To avoid code duplications across modules, possible we want to move this extensions to Core module.

**Comment by tatarincev** [comment]
No longer relevant for 3.0.0 version
