### ISSUE TITLE
Proposal: Refactor indexed *SearchService abstractions

### ISSUE THREAD

**Issue by asvishnyakov** [VirtoCommerce/vc-module-core#19]
[Customer module](https://github.com/VirtoCommerce/vc-module-customer/blob/master/VirtoCommerce.CustomerModule.Data/Search/MemberIndexedSearchService.cs#L13) and [Catalog module](https://github.com/VirtoCommerce/vc-module-catalog/blob/master/VirtoCommerce.CatalogModule.Data/Search/CatalogSearchService.cs) has indexed *SearchService abstractions, which have similar structure:
- SearchAsync
- GetRequestBuilder
- ConvertDocuments

Find Store module will has them too. Shouldn't we create special interface(s) (per module or in search domain model in Core module) and register this classes in Unity as implementations of this interface to allow override them?

**Comment by tatarincev** [comment]
No longer relevant for 3.0.0 version
