### ISSUE TITLE
Allow to request specific fields from the search engine

### ISSUE THREAD

**Issue by artem-dudarev** [VirtoCommerce/vc-module-core#21]
Currently, when you send a request to the search engine, you get the whole indexed documents in the response, so the response is huge.

We need to extend the `VirtoCommerce.Domain.Search.SearchRequest` with a list of fields to be returned from the search engine. This will allow to significantly reduce the size of the response if you only need a few short text fields.

**Comment by tatarincev** [comment]
This feature request has been closed and added to the internal product backlog. 
https://virtocommerce.atlassian.net/browse/PRD-47
