### ISSUE TITLE
SequenceUniqueNumberGeneratorServiceImpl should start at 1 not 0

### ISSUE THREAD

**Issue by OlegoO** [VirtoCommerce/vc-module-core#26]
Currently, Order reference number starts with 0 for a day (ex: HA171213-00000). Instead of starting the reference sequence number from 0, please change the settings to start with 1.

1 as is typical in everyday non-mathematical/non-programming circumstances. 

Version info: 
- Module version: 
v2.24.20

### Expected behavior
initial element of a sequence is assigned the 1

### Actual behavior
initial element of a sequence is assigned the 0

**Comment by tatarincev** [comment]
I've moved this issue to a special milestone and will work on it with other notifications improvements.

**Comment by Woland2k** [comment]
@tatarincev this is not a notification issue, I think u meant to put this comment in a different ticket

**Comment by OlegoO** [comment]
Fixed in https://github.com/VirtoCommerce/vc-module-core/releases/tag/v2.24.21
