### ISSUE TITLE
Make Member addresses extendable.

### ISSUE THREAD

**Issue by busbina** [VirtoCommerce/vc-module-core#3]
I am working with a system that needs custom address types attached to Members, the 3 provided in the AddressType enum are not enough, and do not represent the data we are storing. Also a dynamic properties field would be helpful as well.

**Comment by tatarincev** [comment]
Change AddressType to string should help.

**Comment by tatarincev** [comment]
- [x] Add extension support for the member address
- [ ] Convert current Address edit blade to meta form

**Comment by tatarincev** [comment]
https://github.com/VirtoCommerce/vc-module-customer/commit/6bb6514a986c42b30be6d71a48adc92df3081f96
