### ISSUE TITLE
Why RunIndexJobAsync is not async?

### ISSUE THREAD

**Issue by artem-dudarev** [VirtoCommerce/vc-module-core#30]
https://github.com/VirtoCommerce/vc-module-core/blob/master/VirtoCommerce.CoreModule.Web/BackgroundJobs/IndexingJobs.cs#L240-L283

I've refactored this method to be more readable and to have a single return, but it still has one issue.
There is a loop with a Wait() call which blocks current thread until the task has completed, making the entire indexing process synchronous.
```
foreach (var options in allOptions)
{
    indexationFunc(options, new JobCancellationTokenWrapper(cancellationToken)).Wait();
}
```
Can we change it to `await indexationFunc(...);`?
I didn't do this myself because of this comment:
```
// CAUTION: locking mechanism assumes single threaded execution.
```
Since `async` can continue on a different thread I decided to not touch this loop.

And one more confusing comment:
```
catch
{
    // TODO: Check wait in calling method
    _progressHandler.AlreadyInProgress();
}
```
What does it mean?

**Comment by WimVergouwe** [comment]
I don't think we can easily use async because Hangfire depends on thread local storage: https://github.com/HangfireIO/Hangfire/blob/master/src/Hangfire.SqlServer/SqlServerDistributedLock.cs
We could of course try to get it working through a custom synchronization context, but I don't think that's worth the effort.

The comment is indeed confusing and doesn't seem accurate anymore. I think it can be removed.

**Comment by artem-dudarev** [comment]
Well, based on SqlServerDistributedLock.cs I can tell we CAN use async because there is no dependency on any thread.
https://github.com/HangfireIO/Hangfire/blob/master/src/Hangfire.SqlServer/SqlServerDistributedLock.cs#L197-L203
It just calls a stored procedure 'sp_getapplock', and the result greater than 0 means the lock is acquired.

The `ThreadLocal<Dictionary<string, int>> AcquiredLocks` dictionary is not being used.

**Comment by artem-dudarev** [comment]
But we need to update the Hangfire.SqlServer to version 1.6.17 in the platform first.
Currently used version 1.6.14 still uses this AcquiredLocks.

**Comment by tatarincev** [comment]
Seems this issue is no longer relevant because of 3.0 version includes these modifications.
