### ISSUE TITLE
Change icon for Indexation push notification

### ISSUE THREAD

**Issue by tatarincev** [VirtoCommerce/vc-module-core#33]
Client question:
 In the notification panel when the system has a new "indexation process" the icon of it is a warning sign instead of a success sign. This is for me a bit strange. Can you explain to me why this is a warning sign?

![image](https://user-images.githubusercontent.com/7566324/35043641-fd281914-fb95-11e7-843e-df7ce52fb32c.png)
Need to change notification icon for this type of push notification to something different.

**Comment by n2pro** [comment]
Changed the icon for build search index
![capture](https://user-images.githubusercontent.com/13115017/36310981-6d735d92-1332-11e8-85f4-c7547442da74.JPG)

**Comment by tatarincev** [comment]
Released https://github.com/VirtoCommerce/vc-module-core/releases/tag/v2.24.28
