### ISSUE TITLE
Add Dynamic properties support for Shipment and Payment in Cart

### ISSUE THREAD

**Issue by asvishnyakov** [VirtoCommerce/vc-module-core#42]
Order's Shipment and Payment already has support dynamic properties. If we want to use them to allow users specific additional data for managers on platform, for example, and display in theme UI, then we should first pass this values to dynamic properties of Shipment or Payment of Cart. But they doesn't exist.

**Comment by tatarincev** [comment]
Released https://github.com/VirtoCommerce/vc-module-core/releases/tag/v2.25.0
