### ISSUE TITLE
Add support of shipping method rate details

### ISSUE THREAD

**Issue by asvishnyakov** [VirtoCommerce/vc-module-core#57]
GIVEN I have shipping method rate WHEN I display this rate in UI THEN I want to show details of this rate

**Comment by asvishnyakov** [comment]
@tatarincev @ksavosteev May provide sample code from client project

**Comment by tatarincev** [comment]
This issue has been closed because it has been inactive for  a long time
You may reopen this issue if it has been closed in error.
