### ISSUE TITLE
Search should correctly handle "no search provider" situation

### ISSUE THREAD

**Issue by asvishnyakov** [VirtoCommerce/vc-module-core#61]
Version info: 
- Browser version: Chrome 66
- Platform version: 2.13.26
- Module version: 2.24.32

### Expected behavior
If no search provider registered, or search provider from connection string not found, the appropriate exception should be thrown.

### Actual behavior
![img_18052018_141808_0](https://user-images.githubusercontent.com/6369252/40244104-67264cc4-5adb-11e8-8c53-8d69927c668b.png)

### Steps to reproduce
Uninstall all search providers from fresh installation or set provider in connection string to different than module installed (i.e. `provider=Elasticsearch` while Lucene search installed).

**Comment by asvishnyakov** [comment]
@tatarincev Very confuse new workers

**Comment by tatarincev** [comment]
Already fixed in 3.0 platform version
