### ISSUE TITLE
Search doesn't show error if some of jobs failed when scale out enabled

### ISSUE THREAD

**Issue by asvishnyakov** [VirtoCommerce/vc-module-core#70]
@asvishnyakov commented on [Fri Jun 15 2018](https://github.com/VirtoCommerce/vc-module-elastic-search/issues/5)

I have 12750 members, but was indexed less because of db connection errors. Blade still show "successful" status yet.

**Comment by yecli** [comment]
[v2.25.20](https://github.com/VirtoCommerce/vc-module-core/releases/tag/v2.25.20)
