### ISSUE TITLE
Mark required properties as required in domain models

### ISSUE THREAD

**Issue by asvishnyakov** [VirtoCommerce/vc-module-core#86]
**Problem:**
Currently there is no way to determine which properties is required for object and which is not. It's very unuseful especially when you work with code generated by AutoRest or want to use power of code analysis tools like ReSharper.

**Solution:**
Need to find the way to mark required properties as required in domain models and generated AutoRest clients.

**Comment by tatarincev** [comment]
This issue has been closed because it has been inactive for  a long time
You may reopen this issue if it has been closed in error.
