### ISSUE TITLE
Extend search syntax with boolean operators

### ISSUE THREAD

**Issue by asvishnyakov** [VirtoCommerce/vc-module-core#89]
Currently we support a limited number of operations on search field values, like AND (color:Black color:White) or OR (color:Black,White). Please, replace it with more formal syntax (and, or, not, xor keywords) and allow to do all of these operations on properties (currently I can't write query for color:Black OR brand:Microsoft). Also, allow to use parentheses.

Alternative is to allow write queries on search engine language, but I will prefer avoid it because it will complicate moving from one search engine to another: for example, in our current project we use Elastic Search but may move to Azure Search in near future.

**Comment by tatarincev** [comment]
This feature request has been closed and added to the internal product backlog. 
https://virtocommerce.atlassian.net/browse/PRD-47
