### ISSUE TITLE
SEO info still used for routing even if disabled

### ISSUE THREAD

**Issue by asvishnyakov** [VirtoCommerce/vc-module-core#97]
Version info: 
- Browser version: Chrome 70
- Platform version: 2.13.37
- Module version: 2.25.17

### Expected behavior
If seo disabled, it shouldn't be used for routing

### Actual behavior
Seo used for routing even if disabled

### Steps to reproduce
1. Go to demo site
2. Open any product
3. Copy seo path
4. Open demo.virtocommerce.com/product_seo_path
5. Product page opens
6. Remove seo for product
7. Open demo.virtocommerce.com/product_seo_path
8. 404 error page appear
9. Open previously used product
10. Add copied seo path
11. Disable this SEO
12. Open demo.virtocommerce.com/product_seo_path

Expected: 404 error should be returned
Actual: product page opens

**Comment by artem-dudarev** [comment]
> 10. Add copied seo path
> Expected: 404 error should be returned

Why do you expect the 404 error when you add SEO path to a product?

**Comment by asvishnyakov** [comment]
@artem-dudarev Important step was missed :)

**Comment by tatarincev** [comment]
This feature request has been closed and added to the internal product backlog. 
https://virtocommerce.atlassian.net/browse/PRD-94
