### ISSUE TITLE
Allow to delete only single product from index, not all the index

### ISSUE THREAD

**Issue by asvishnyakov** [VirtoCommerce/vc-module-core#99]
Now of you will both specify DocumentIds & DeleteExistingIndex=true in options it will remove FULL index, not only documents which you specified. Add ability to do that. It may be helpful in situation when you want to remove index variation, for example.

**Comment by tatarincev** [comment]
This feature request has been closed and added to the internal product backlog.
https://virtocommerce.atlassian.net/browse/PRD-47
